name: docs
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install --no-cache-dir Cython
                  pip install -r requirements.txt -r requirements_dev.txt
                  pip install .
            - name: Discover typos with codespell
              run: |
                  codespell --skip="*.csv,*.geojson,*.json,*.js,*.html,*cff,./.git,*.txt,*.data_types.ipynb" --ignore-words-list="aci,hist,vor,voronoi_adjacency_distance"
            - name: PKG-TEST
              run: |
                  python -m unittest discover tests/
            - run: mkdocs gh-deploy --force

